"""Draw a synthetic illustration of the source-separation problem for the README.

The fields are generated here with NumPy only (no research data): a long-wavelength
Rossby-wave sea-surface-height signal, a short-wavelength internal-wave component,
their sum, and a SWOT-style two-sided swath sampling the sum. It illustrates the
task; it is not a model result.

    python scripts/make_figures.py
"""

from __future__ import annotations

import os
from pathlib import Path

os.environ.setdefault("MPLBACKEND", "Agg")

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
FIG_DIR = ROOT / "docs" / "figures"


def fields(size_km: float = 1000.0, n: int = 200, seed: int = 7):
    rng = np.random.default_rng(seed)
    x = np.linspace(0, size_km, n)
    y = np.linspace(0, size_km, n)
    X, Y = np.meshgrid(x, y)
    rossby = np.zeros_like(X)
    for wavelength, amp, angle in ((520, 6.0, 0.25), (380, 4.0, -0.35), (640, 3.0, 0.05)):
        k = 2 * np.pi / wavelength
        rossby += amp * np.cos(k * (X * np.cos(angle) + Y * np.sin(angle)) + rng.uniform(0, 2 * np.pi))
    internal = np.zeros_like(X)
    for _ in range(14):
        wavelength = rng.uniform(60, 140)
        k = 2 * np.pi / wavelength
        angle = rng.uniform(0, np.pi)
        internal += rng.uniform(0.8, 1.6) * np.cos(k * (X * np.cos(angle) + Y * np.sin(angle)) + rng.uniform(0, 2 * np.pi))
    return x, y, rossby, internal


def swath_mask(x, y, half_width_km: float = 60.0, gap_km: float = 10.0, tilt_deg: float = 15.0):
    X, Y = np.meshgrid(x, y)
    tilt = np.deg2rad(tilt_deg)
    # perpendicular distance from the ground track through the domain centre
    d = (X - x.mean()) * np.cos(tilt) - (Y - y.mean()) * np.sin(tilt)
    return (np.abs(d) <= half_width_km) & (np.abs(d) >= gap_km)


def main() -> None:
    mpl.rcParams.update({
        "font.family": "sans-serif", "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
        "font.size": 9, "axes.labelsize": 9, "axes.titlesize": 9.5, "xtick.labelsize": 8,
        "ytick.labelsize": 8, "axes.linewidth": 0.6, "savefig.bbox": "tight", "savefig.pad_inches": 0.03,
    })
    x, y, rossby, internal = fields()
    mixed = rossby + internal
    mask = swath_mask(x, y)
    sampled = np.where(mask, mixed, np.nan)
    vmax = float(np.abs(mixed).max())

    fig, axes = plt.subplots(1, 4, figsize=(9.6, 2.75), constrained_layout=True)
    panels = [
        (rossby, "Rossby-wave SSH (target)"),
        (internal, "internal-wave component"),
        (mixed, "mixed field"),
        (sampled, "SWOT-style swath sampling"),
    ]
    for ax, (field, title) in zip(axes, panels):
        im = ax.imshow(field, origin="lower", extent=(x[0], x[-1], y[0], y[-1]), cmap="RdBu_r",
                       vmin=-vmax, vmax=vmax, interpolation="nearest")
        ax.set_title(title)
        ax.set_xlabel("x (km)")
        ax.set_xticks([0, 500, 1000])
        ax.set_yticks([0, 500, 1000])
    axes[0].set_ylabel("y (km)")
    for ax in axes[1:]:
        ax.set_yticklabels([])
    axes[3].set_facecolor("0.93")
    cbar = fig.colorbar(im, ax=axes, fraction=0.02, pad=0.01)
    cbar.set_label("sea-surface height anomaly (cm)")
    for ax, tag in zip(axes, "abcd"):
        ax.text(0.03, 0.96, f"({tag})", transform=ax.transAxes, fontweight="bold", va="top")
    fig.text(0.005, 0.01, "synthetic illustration of the separation task, generated by scripts/make_figures.py",
             fontsize=7, color="0.4")
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIG_DIR / "separation_task.png", dpi=200)
    print("wrote docs/figures/separation_task.png")


if __name__ == "__main__":
    main()
